apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../deploy/manifests

namespace: default
nameSuffix: -darwinia
commonLabels:
  app: kubevali
  chain: darwinia

images:
  - name: quay.io/darwinia-network/kubevali
    newTag: sha-3bf7399
  - name: quay.io/darwinia-network/darwinia
    newTag: v0.8.2
  - name: quay.io/darwinia-network/node-liveness-probe
    newTag: v0.3.0

configMapGenerator:
  - name: kubevali
    files:
      - kubevali.yaml
