apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/clusterrole.yaml
  - manifests/clusterrolebinding.yaml
  - manifests/serviceaccount.yaml
  - manifests/statefulset.yaml

nameSuffix: -darwinia
commonLabels:
  app: kubevali
  chain: darwinia

images:
  - name: quay.io/darwinia-network/kubevali
    newTag: sha-3bf7399
  - name: quay.io/darwinia-network/darwinia
    newTag: v0.8.2

configMapGenerator:
  - name: kubevali
    files:
      - kubevali.yaml
